name: my_dataset
description: A test dataset for datarade

endpoint:
    driver: mssql
    host: my_host
    port: 12345
    database: my_database

fields:
    - name: my_string_field
      type: String
    - name: my_integer_field
      type: Integer
