name: my_dataset
description: A test dataset for datarade

database:
    driver: mssql
    host: my_host
    port: 12345
    name: my_database
    schema: dbo

fields:
    - name: my_string_field
      type: String
    - name: my_integer_field
      type: Integer
