name: my_github_dataset
description: A test dataset for datarade hosted on github

database:
    driver: mssql
    host: my_host
    port: 12345
    database_name: my_github_integration_database
    schema_name: dbo

fields:
    - name: my_string_field
      type: String
    - name: my_integer_field
      type: Integer
