name: my_github_dataset_with_user
description: A test dataset with a named user for datarade hosted on github

database:
    driver: mssql
    host: my_host
    port: 12345
    database_name: my_github_database
    schema_name: dbo

user:
    username: pytest_user

fields:
    - name: my_string_field
      type: String
    - name: my_integer_field
      type: Integer
