name: my_other_dataset
description: Another test dataset for datarade

endpoint:
    driver: mssql
    host: my_host
    port: 12345
    database: my_database

fields:
    - name: my_other_string_field
      type: String
    - name: my_other_integer_field
      type: Integer
