name: my_other_github_dataset
description: Another test dataset for datarade hosted on github

database:
    driver: mssql
    host: my_host
    port: 12345
    database_name: my_other_github_database
    schema_name: dbo

fields:
    - name: my_other_string_field
      type: String
    - name: my_other_integer_field
      type: Integer
